### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by luftek** [zerog2k/stc_diyclock#24]
Thank you for sharing here!
I will try to reuse this project, same MCU is used in:
https://www.banggood.com/Digital-Soldering-Iron-Station-Temperature-Controller-Kits-for-HAKKO-T12-Handle-p-993248.html

**Comment by zerog2k** [comment]
Cool, once you have something working, let me know the repo, as I would love to see how it works... (I already have a Hakko FX888D which was worth every penny, or else I might pick that one up ;)
