### ISSUE TITLE
Need help with make on windows

### ISSUE THREAD

**Issue by Ing-Med** [zerog2k/stc_diyclock#35]
Hi there,
unfortunately i am too stupid to compile the code on windows. Tried it on a ubuntu VM too, but no luck.
Under windows i can't just get a .hex file out of the makefile. it only prints out many others amongst the main.ihx.
Would you be so nice and upload a compiled version?
The complied version from zerog2k uploaded just fine.

Thanks

**Comment by zerog2k** [comment]
sorry for the late response, but (infrequently) I am uploading the binaries (.hex fw). Click on `releases` section of repo to find them.
