### ISSUE TITLE
My kit reset time to 00:00  01-01-2000 each power cycle

### ISSUE THREAD

**Issue by IgorTrud** [zerog2k/stc_diyclock#59]
I checked battery voltage on DS1302 directy - fine 2.98V
I checked XTAL - running nicely at 32 kHz even in no-power state.
Any ideas what could be wrong ? 
Is there any FUSE bits, what need to be set during MCU flashing to avoid this ?

Chip is 15W404AS. I have the same issue on "original" chinise firmware too...

**Comment by zerog2k** [comment]
>I have the same issue on "original" chinise firmware too

some hardware issue - mcu maybe cannot talk to ds1302
usually missing pullup/pulldown, or problem with clock/data lines.
maybe problem during assembly - recheck schematics, soldering, etc.

**Comment by IgorTrud** [comment]
Yes, it was HW issue.
DS1302 should have some capacitance on Vcc and Vbat pin, otherwise it resets during switch.
No software issues, closing.
